image: python2.7
env:
  - GOPATH=/var/cache/drone
script:
  - pip install .
  - pip install -r .travis_requirements --use-mirrors
  - pip install coverage
  - nosetests --with-coverage --cover-package informant
